/**
 * Belladonna's Parlour — scenario-bank provider + manifest conformance tests.
 * The bank is generated by the Python engine (single math source of truth);
 * these tests prove the client accepts and correctly handles every manifest.
 */

import { describe, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { ScenarioBankProvider, type ScenarioBank } from '../src/core/scenarioBankProvider.js';
import { assertValidManifest, stepsWinTotalMinor, validateManifest } from '../src/core/roundProvider.js';
import { buildRecoveryPlan } from '../src/core/recovery.js';

const bank = JSON.parse(
  readFileSync(join(import.meta.dir, '..', 'scenarios', 'dev-bank.json'), 'utf8'),
) as ScenarioBank;

describe('scenario bank conformance', () => {
  test('bank metadata is present and dev-flagged', () => {
    expect(bank.meta.gameId).toBe('belladonna-parlour');
    expect(bank.meta.configHash).toStartWith('sha256:');
    expect(bank.meta.generator).toContain('DEV ONLY');
    expect(bank.manifests.length).toBe(bank.meta.count);
  });

  test('every manifest in the bank passes full client validation', () => {
    for (const m of bank.manifests) {
      const issues = validateManifest(m);
      expect(issues).toEqual([]);
    }
  });

  test('totals equal the sum of win entries for uncapped rounds', () => {
    for (const m of bank.manifests) {
      if (!m.capped) expect(stepsWinTotalMinor(m)).toBe(m.totalWinMinor);
    }
  });

  test('tier mapping 3/4/5+ holds across the bank', () => {
    for (const m of bank.manifests) {
      if (!m.feature) continue;
      const sc = m.feature.triggerScatterCount;
      if (sc === 3) expect(m.feature.tierId).toBe('feature');
      else if (sc === 4) expect(m.feature.tierId).toBe('super_feature');
      else expect(m.feature.tierId).toBe('ultimate_feature');
      expect(m.feature.retriggerCount).toBeLessThanOrEqual(m.feature.retriggerCap);
    }
  });

  test('bank contains all three tiers (forced scenarios included)', () => {
    const tiers = new Set(bank.manifests.filter((m) => m.feature).map((m) => m.feature!.tierId));
    expect(tiers).toEqual(new Set(['feature', 'super_feature', 'ultimate_feature']));
  });

  test('orb-multiplier settlement is exact: MULT delta entries only on winning sequences', () => {
    let multEntries = 0;
    for (const m of bank.manifests) {
      for (const step of m.steps) {
        for (const win of step.wins) {
          if (win.symbolId === 'MULT') {
            multEntries += 1;
            // a multiplier delta can only exist when the sequence paid something
            const seqPays = m.steps.some((s) => s.wins.some((w) => w.symbolId !== 'MULT' && w.symbolId !== 'SCATTER'));
            expect(seqPays).toBe(true);
            expect(win.winMinor).toBeGreaterThan(0);
          }
        }
      }
    }
    expect(multEntries).toBeGreaterThan(10); // orb applications are common
  });
});

describe('ScenarioBankProvider', () => {
  test('deterministic: same seed ⇒ same round sequence', async () => {
    const a = new ScenarioBankProvider(bank, 42);
    const b = new ScenarioBankProvider(bank, 42);
    for (let i = 0; i < 20; i++) {
      const ma = await a.requestRound(100);
      const mb = await b.requestRound(100);
      expect(ma.roundId).toBe(mb.roundId);
    }
  });

  test('different seeds diverge', async () => {
    const a = new ScenarioBankProvider(bank, 1);
    const b = new ScenarioBankProvider(bank, 2);
    const ids = await Promise.all([
      Promise.all(Array.from({ length: 10 }, () => a.requestRound(100).then((m) => m.roundId))),
      Promise.all(Array.from({ length: 10 }, () => b.requestRound(100).then((m) => m.roundId))),
    ]);
    expect(ids[0].join(',')).not.toBe(ids[1].join(','));
  });

  test('idempotency: same key returns the identical committed round, no new wager', async () => {
    const p = new ScenarioBankProvider(bank, 7);
    const first = await p.requestRound(100, { idempotencyKey: 'tx-1' });
    const served = p.roundsServed;
    const replay = await p.requestRound(100, { idempotencyKey: 'tx-1' });
    expect(replay).toEqual(first);
    expect(p.roundsServed).toBe(served); // no additional pick
  });

  test('bonus-buy requests return the requested tier', async () => {
    const p = new ScenarioBankProvider(bank, 9);
    for (const tier of ['feature', 'super_feature', 'ultimate_feature'] as const) {
      const m = await p.requestRound(100, { bonusBuyTier: tier });
      expect(m.feature?.tierId).toBe(tier);
    }
  });

  test('rejects non-bank stakes (dev limitation, documented)', async () => {
    const p = new ScenarioBankProvider(bank, 3);
    await expect(p.requestRound(250)).rejects.toThrow(/betMinor=100/);
  });

  test('recovery: staged interrupted round resumes at the pointer without re-settling', async () => {
    const p = new ScenarioBankProvider(bank, 11);
    const withFeature = bank.manifests.find((m) => m.feature && m.steps.length > 6)!;
    const mid = withFeature.steps[Math.floor(withFeature.steps.length / 2)]!.stepId;
    p.stageInterrupted(withFeature, mid);
    const resumed = await p.resume();
    expect(resumed).not.toBeNull();
    const plan = buildRecoveryPlan(resumed!.manifest, resumed!.resumePointer);
    expect(resumed!.manifest.steps[plan.resumeStepIndex]!.stepId).toBe(mid);
    expect(resumed!.manifest.totalWinMinor).toBe(withFeature.totalWinMinor); // never re-settled
    expect(await p.resume()).toBeNull(); // consumed
  });

  test('served manifests are clones — mutating one never corrupts the bank', async () => {
    const p = new ScenarioBankProvider(bank, 13);
    const m = await p.requestRound(100);
    const original = bank.manifests.find((x) => x.roundId === m.roundId)!;
    m.totalWinMinor = 999999999;
    (m.steps[0]!.grid[0] as string[])[0] = 'HACK';
    expect(original.totalWinMinor).not.toBe(999999999);
    assertValidManifest(original);
  });
});
