/**
 * Belladonna's Parlour dev entrypoint (DEV ONLY).
 *
 * Exports a `bootstrapApp` that wraps the template's: it loads the scenario
 * bank and injects ScenarioBankProvider, so index.html's boot call
 * (`bootstrapApp({ mount })`) runs THIS game. Every outcome is a committed
 * manifest pre-generated by the Python math engine — the client stays a pure
 * renderer, matching the production posture with the RGS swapped for the bank.
 *
 * Served by scripts/serve.ts as /app.js. Placeholder sprites (no generated
 * art yet); grids, cascades, orb-multiplier deltas, tier entries, win tiers,
 * autoplay and recovery are real and manifest-driven.
 */

import { Assets, type Texture } from 'pixi.js';

import type { AppOptions, SlotApp } from './app.js';
import { bootstrapApp as bootstrapTemplate } from './app.js';
import { ScenarioBankProvider, type ScenarioBank } from '../core/scenarioBankProvider.js';

const SYMBOL_IDS = [
  'SCATTER', 'MULT', 'FX1', 'H1', 'H2', 'H3', 'H4', 'L1', 'L2', 'L3', 'L4', 'L5',
] as const;

/** Load the Blender-rendered symbol sprites; missing files degrade to placeholders. */
async function loadSymbolTextures(): Promise<ReadonlyMap<string, Texture>> {
  const map = new Map<string, Texture>();
  await Promise.all(
    SYMBOL_IDS.map(async (id) => {
      try {
        const tex = (await Assets.load(`assets/symbols/${id.toLowerCase()}.png`)) as Texture;
        map.set(id, tex);
      } catch {
        // silent-safe: reelView renders a labelled placeholder for this id
      }
    }),
  );
  return map;
}

export async function bootstrapApp(options: AppOptions): Promise<SlotApp> {
  const res = await fetch('scenarios/dev-bank.json');
  if (!res.ok) {
    throw new Error(`scenario bank not served (${res.status}) — run math-config/wire_client_demo.py`);
  }
  const bank = (await res.json()) as ScenarioBank;
  // eslint-disable-next-line no-console
  console.info(
    `[belladonna] DEV scenario bank: ${bank.meta.count} committed rounds ` +
      `(${bank.meta.configHash.slice(0, 20)}…) — DEV ONLY, never a real RGS.`,
  );
  const provider = new ScenarioBankProvider(bank, Date.now() >>> 0);
  const symbolTextures = await loadSymbolTextures();
  // eslint-disable-next-line no-console
  console.info(`[belladonna] symbol textures loaded: ${symbolTextures.size}/${SYMBOL_IDS.length}`);
  return bootstrapTemplate({ configBaseUrl: 'config/', symbolTextures, ...options, provider });
}

export { SlotApp } from './app.js';
