"""Produces sample-outcome-manifest.json: one representative super_feature
round generated by the actual slot_math engine (dev round provider path).

The engine's internal round dict is close to, but not exactly, the
outcome-manifest schema shape; a real skill run's specialized engine emits the
schema shape directly. The documented post-processing here (see ../README.md):

  1. feature steps move from the flat steps[] into feature.steps[] as step
     OBJECTS (the template engine stores only their stepIds in the feature
     block); stepIds keep their manifest-wide strict ordering.
  2. per-step stepWinMinor (an engine convenience) is dropped - the schema
     carries win amounts only inside wins[].
  3. the engine's feature.totalWinMinor convenience field is dropped;
     remainingRounds is 0 (committed, fully settled round).

Entry uses the DEV-ONLY forced-scatter hook (forced={"scatterCount": 4}) so the
sample deterministically shows the super_feature tier; production outcomes come
only from the RGS (CONVENTIONS 9.1).

Run from the skill's math/ directory:
  uv run python ../examples/example-single-slot/make_sample_manifest.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).parent
sys.path.insert(0, str(HERE.parent.parent / "math" / "src"))

from slot_math.config import load_config  # noqa: E402
from slot_math.engine import play_round  # noqa: E402
from slot_math.rng import make_rng  # noqa: E402

SEED = 20260808
FEATURE_STEP_TYPES = {"feature_round", "feature_retrigger", "max_win_termination"}


def main() -> None:
    config = load_config(HERE / "math-config")
    rng = make_rng(SEED)
    m = play_round(config, rng, bet_minor=100, round_id="rnd_example_super_0001",
                   forced={"scatterCount": 4})
    assert m["feature"]["triggered"] and m["feature"]["tier"] == "super_feature"

    base_steps, feature_steps = [], []
    for step in m["steps"]:
        step.pop("stepWinMinor", None)
        (feature_steps if step["type"] in FEATURE_STEP_TYPES else base_steps).append(step)

    manifest = {
        "schemaVersion": m["schemaVersion"],
        "roundId": m["roundId"],
        "gameId": m["gameId"],
        "gameVersion": m["gameVersion"],
        "mathVersion": m["mathVersion"],
        "mathProfileId": m["mathProfileId"],
        "configHash": m["configHash"],
        "currency": "EUR",
        "wagerMinor": m["wagerMinor"],
        "initialGrid": m["initialGrid"],
        "steps": base_steps,
        "feature": {
            "triggered": True,
            "tier": m["feature"]["tier"],
            "initialRounds": m["feature"]["initialRounds"],
            "remainingRounds": 0,
            "steps": feature_steps,
            "retriggers": m["feature"]["retriggers"],
            "maxWinReached": m["feature"]["maxWinReached"],
        },
        "totalWinMinor": m["totalWinMinor"],
        "maximumWinReached": m["maximumWinReached"],
        "roundComplete": True,
        "signature": "dev-unsigned",
    }
    out = HERE / "sample-outcome-manifest.json"
    out.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {out.name}: tier={manifest['feature']['tier']} "
          f"steps={len(base_steps)}+{len(feature_steps)} totalWinMinor={manifest['totalWinMinor']} "
          f"(bet 100 -> {manifest['totalWinMinor'] / 100:.2f}x)")


if __name__ == "__main__":
    main()
