/**
 * ScenarioBankProvider — Belladonna's Parlour DEV round provider.
 *
 * Replays committed outcome manifests pre-generated by the Python math engine
 * (math-config/export_dev_bank.py). This is the game's deterministic
 * development/QA outcome source: the scatter-pays + orb-multiplier math lives
 * server-side (here: in the simulator), and the client stays a pure renderer —
 * exactly the production posture, with the RGS swapped for a canned bank.
 *
 * DEV ONLY. Refuses to construct in production builds. The bank embeds the
 * configHash it was generated from; a mismatched hash must be treated as a
 * stale bank (regenerate via `uv run python ../math-config/export_dev_bank.py`).
 */

import type { OutcomeManifest, TierId } from './types.js';
import type { RequestRoundOptions, ResumeResult, RoundProvider } from './roundProvider.js';
import { assertValidManifest } from './roundProvider.js';

export interface ScenarioBank {
  meta: {
    generator: string;
    gameId: string;
    configHash: string;
    seedPolicy: string;
    betMinor: number;
    count: number;
  };
  manifests: OutcomeManifest[];
}

/** splitmix32 — tiny deterministic sequencer for bank order (DEV only). */
function splitmix32(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x9e3779b9) >>> 0;
    let z = state;
    z = Math.imul(z ^ (z >>> 16), 0x21f0aaad);
    z = Math.imul(z ^ (z >>> 15), 0x735a2d97);
    return ((z ^ (z >>> 15)) >>> 0) / 0x100000000;
  };
}

export class ScenarioBankProvider implements RoundProvider {
  private readonly next: () => number;
  private readonly byIdempotencyKey = new Map<string, OutcomeManifest>();
  private pendingInterrupted: ResumeResult | null = null;
  private served = 0;

  constructor(
    private readonly bank: ScenarioBank,
    seed = 1,
  ) {
    if (typeof process !== 'undefined' && process.env.NODE_ENV === 'production') {
      throw new Error('ScenarioBankProvider is DEV-ONLY and must never ship in production');
    }
    if (!bank.manifests.length) throw new Error('scenario bank is empty');
    this.next = splitmix32(seed);
  }

  /** Deep copy so presentation code can never mutate the bank. */
  private clone(m: OutcomeManifest): OutcomeManifest {
    return JSON.parse(JSON.stringify(m)) as OutcomeManifest;
  }

  private pick(predicate?: (m: OutcomeManifest) => boolean): OutcomeManifest {
    const pool = predicate ? this.bank.manifests.filter(predicate) : this.bank.manifests;
    if (!pool.length) throw new Error('no scenario in bank matches the request');
    const idx = Math.floor(this.next() * pool.length);
    this.served += 1;
    return pool[idx]!;
  }

  async requestRound(betMinor: number, opts?: RequestRoundOptions): Promise<OutcomeManifest> {
    if (betMinor !== this.bank.meta.betMinor) {
      throw new RangeError(
        `scenario bank was generated at betMinor=${this.bank.meta.betMinor}; ` +
          `dev mode serves only that stake (requested ${betMinor})`,
      );
    }
    if (opts?.idempotencyKey) {
      const prior = this.byIdempotencyKey.get(opts.idempotencyKey);
      if (prior) return this.clone(prior); // duplicate request ⇒ original result, no new wager
    }
    const tier: TierId | undefined = opts?.bonusBuyTier;
    const manifest = this.pick(tier ? (m) => m.feature?.tierId === tier : undefined);
    assertValidManifest(manifest);
    if (opts?.idempotencyKey) this.byIdempotencyKey.set(opts.idempotencyKey, manifest);
    return this.clone(manifest);
  }

  async resume(): Promise<ResumeResult | null> {
    const pending = this.pendingInterrupted;
    this.pendingInterrupted = null;
    return pending;
  }

  /**
   * TEST/QA hook: stage an interrupted committed round so `resume()` exercises
   * the recovery path (seek to resumePointer; never re-settle).
   */
  stageInterrupted(manifest: OutcomeManifest, resumePointer: string): void {
    if (!manifest.steps.some((s) => s.stepId === resumePointer)) {
      throw new RangeError(`resumePointer ${resumePointer} not in round ${manifest.roundId}`);
    }
    this.pendingInterrupted = { manifest: this.clone(manifest), resumePointer };
  }

  get roundsServed(): number {
    return this.served;
  }
}
